version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ejada_leave
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: ["db_data:/var/lib/postgresql/data"]
  api:
    build:
      context: ../
      dockerfile: infra/Dockerfile.api
    environment:
      ENV: local
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: ejada_leave
      AWS_REGION: ap-south-1
      JWT_SECRET: SUPER_SECRET_CHANGE
    ports: ["8000:8000"]
    depends_on: [db]
  web:
    build:
      context: ../
      dockerfile: infra/Dockerfile.web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports: ["3000:3000"]
    depends_on: [api]
volumes:
  db_data:
